---
fullname: EdwardsEllipticCurve
shortname: EdwardsEllipticCurve
organization: thery
opam_name: coq-edwards
community: false
dune: false
action: true

synopsis:  Edwards Curves

description: |-

  Following The Group Law for Edwards Curves Thomas C. Hales

authors:
- name: Laurent Théry

maintainers:
- name: Laurent Théry
  nickname: thery

opam-file-maintainer: thery@sophia.inria.fr

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: '9.0 or later'
  opam: '{(>= "9.0")}'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{(>= "2.5.0")}'
  description: |-
    [MathComp ssreflect 2.5 or later](https://math-comp.github.io)

tested_coq_opam_versions:
- version: '2.5.0-rocq-prover-9.0'
  repo: 'mathcomp/mathcomp'

namespace: edwards

keywords:
- name: edwards
- name: elliptic curve
---